packages:
  - "apps/*"
  - "packages/*"

engineStrict: false

overrides:
  "esbuild@<=0.24.2": 0.25.0

allowBuilds:
  esbuild: true
  lefthook: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - '@astrojs/internal-helpers@0.10.3'
  - '@astrojs/react@6.0.3'
  - fumadocs-core@16.14.5
  - fumadocs-ui@16.14.5
  - '@effect/platform-node-shared@4.0.0-rc.112'
  - '@effect/vitest@4.0.0-rc.112'
  - effect@4.0.0-rc.112
